from __future__ import annotations

from app.services.subscription.episode.parser import (
    FULL_SERIES_PACK_RE,
    SEASON_PACK_WORD_RE,
    STRONG_PACK_WORD_RE,
    _all_tmdb_episode_keys,
    _episode_counts_from_pack_text,
    _episode_key,
    _episode_key_from_item,
    _episode_key_from_json,
    _episode_keys_by_season,
    _episode_keys_from_json,
    episode_keys_from_text_for_subscription,
    _expand_episode_range,
    json_episode_key,
    missing_episode_keys,
    _number_token_to_int,
    _pack_episode_keys_from_text,
    _season_keys_for_counts,
    _season_numbers_from_text,
    tmdb_seasons_from_detail,
    episodes_from_text,
)
from app.services.subscription.match.identity import (
    TITLE_PREFIX_LABELS,
    TITLE_SUFFIX_BOUNDARY_CHARS,
    TMDB_ID_RE,
    extra_search_keywords,
    _is_title_prefix_boundary,
    _is_title_suffix_boundary,
    _match_term,
    _release_year_matches,
    _result_has_subscription_tmdb_id,
    result_is_fallback_source,
    _result_is_primary_115_resource,
    _result_is_site_plugin,
    result_priority,
    _result_title_identity_conflicts,
    _subscription_match_text,
    subscription_release_year,
    _subscription_required_terms,
    subscription_search_title,
    _term_in_text,
    _title_fragment_in_text,
    _title_term_in_text,
    _tmdb_ids_from_text,
    _year_guard_texts,
)
from app.services.subscription.match.core import result_matches_subscription
from app.services.subscription.match.quality import (
    _is_pack_result_text,
    _quality_rule_skip_reason,
    _text_contains_any,
    result_matches_quality_rules,
)
from app.services.subscription.resource.resources import resource_dedupe_key as _resource_dedupe_key
from app.services.subscription.match.result_utils import result_debug_payload, result_text
from app.services.subscription.match.skip_reasons import result_skip_reason, skip_reason_summary
from app.services.subscription.match.text_utils import (
    compact_match_text,
    normalize_quality_rules,
    title_without_year,
    years_from_text,
)

__all__ = [
    "FULL_SERIES_PACK_RE",
    "SEASON_PACK_WORD_RE",
    "STRONG_PACK_WORD_RE",
    "TITLE_PREFIX_LABELS",
    "TITLE_SUFFIX_BOUNDARY_CHARS",
    "TMDB_ID_RE",
    "_all_tmdb_episode_keys",
    "compact_match_text",
    "_episode_counts_from_pack_text",
    "_episode_key",
    "_episode_key_from_item",
    "_episode_key_from_json",
    "_episode_keys_by_season",
    "_episode_keys_from_json",
    "episode_keys_from_text_for_subscription",
    "_expand_episode_range",
    "extra_search_keywords",
    "_is_pack_result_text",
    "_is_title_prefix_boundary",
    "_is_title_suffix_boundary",
    "json_episode_key",
    "_match_term",
    "missing_episode_keys",
    "normalize_quality_rules",
    "_number_token_to_int",
    "_pack_episode_keys_from_text",
    "_quality_rule_skip_reason",
    "_release_year_matches",
    "_resource_dedupe_key",
    "result_debug_payload",
    "_result_has_subscription_tmdb_id",
    "result_is_fallback_source",
    "_result_is_primary_115_resource",
    "_result_is_site_plugin",
    "result_priority",
    "result_skip_reason",
    "result_text",
    "_result_title_identity_conflicts",
    "_season_keys_for_counts",
    "_season_numbers_from_text",
    "skip_reason_summary",
    "_subscription_match_text",
    "subscription_release_year",
    "_subscription_required_terms",
    "subscription_search_title",
    "_term_in_text",
    "_text_contains_any",
    "_title_fragment_in_text",
    "_title_term_in_text",
    "title_without_year",
    "_tmdb_ids_from_text",
    "tmdb_seasons_from_detail",
    "_year_guard_texts",
    "years_from_text",
    "episodes_from_text",
    "result_matches_quality_rules",
    "result_matches_subscription",
]
