from pathlib import Path

from fastapi.testclient import TestClient

from app.main import app
from app.tools import build_static


MOJIBAKE_MARKERS = (
    "\u00c3",
    "\u00c2",
    "\u00e4\u00bd",
    "\u00e6",
    "\u00e5",
    "\ufffd",
    "\u9420",
    "\u95b9",
    "\u95b8",
    "\u95c1",
    "\u5a62",
    "\u7025",
    "\u93c3",
    "\u7481",
    "\u93bc",
    "\u934f",
    "\u9422",
    "\u95be",
    "\u7039",
    "\u93b8",
    "\u6fb6",
    "\u935a",
    "\u6434",
    "\u6960",
    "\u9427",
    "\u95c7",
    "\u5bee",
    "\u93c8",
    "\u951b",
    "\u9518",
    "\u9a9e",
)


def _expected_bundle(files: list[str], source_dir: Path, root: Path, header: str) -> str:
    chunks = [header.rstrip(), ""]
    for name in files:
        path = source_dir / name
        chunks.append(f"/* source: {path.relative_to(root).as_posix()} */")
        chunks.append(path.read_text(encoding="utf-8").strip())
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def test_static_bundles_are_generated_from_split_sources():
    expected_js = _expected_bundle(
        build_static.JS_FILES,
        build_static.JS_SRC,
        build_static.ROOT,
        "// Generated by app/tools/build_static.py. Edit app/static/src/js/* instead.",
    )
    expected_css = _expected_bundle(
        build_static.CSS_FILES,
        build_static.CSS_SRC,
        build_static.ROOT,
        "/* Generated by app/tools/build_static.py. Edit app/static/src/css/* instead. */",
    )

    assert (build_static.STATIC / "app.js").read_text(encoding="utf-8") == expected_js
    assert (build_static.STATIC / "styles.css").read_text(encoding="utf-8") == expected_css


def test_static_sources_do_not_contain_common_mojibake_markers():
    source_paths = [
        *build_static.JS_SRC.glob("*.js"),
        *build_static.CSS_SRC.glob("*.css"),
        build_static.STATIC / "app.js",
        build_static.STATIC / "styles.css",
    ]

    issues: list[str] = []
    for path in source_paths:
        text = path.read_text(encoding="utf-8", errors="replace")
        for line_no, line in enumerate(text.splitlines(), start=1):
            marker = next((item for item in MOJIBAKE_MARKERS if item in line), None)
            if marker:
                rel_path = path.relative_to(build_static.ROOT).as_posix()
                escaped_marker = marker.encode("unicode_escape").decode("ascii")
                issues.append(f"{rel_path}:{line_no} contains {escaped_marker}")

    assert issues == []


def test_static_assets_are_served_as_utf8_without_cache():
    client = TestClient(app)

    index_response = client.get("/")
    assert index_response.status_code == 200
    assert 'src="/static/app.js?v=' in index_response.text
    assert 'charset="UTF-8"' in index_response.text
    assert index_response.headers["cache-control"] == "no-store"

    script_response = client.get("/static/app.js")
    assert script_response.status_code == 200
    assert script_response.headers["cache-control"] == "no-store"
    assert script_response.headers["content-type"] == "text/javascript; charset=utf-8"
    assert "片单" in script_response.text
