from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "static"
JS_SRC = STATIC / "src" / "js"
CSS_SRC = STATIC / "src" / "css"

JS_FILES = [
    "00_state.js",
    "10_shell.js",
    "20_tmdb_home.js",
    "21_tmdb_cards.js",
    "22_tmdb_detail.js",
    "30_emby.js",
    "40_subscriptions_view.js",
    "41_subscription_cards.js",
    "42_subscription_resources.js",
    "50_logs.js",
    "60_settings_view.js",
    "61_settings_sources_model.js",
    "62_settings_sources_view.js",
    "63_settings_sources_actions.js",
    "64_settings_actions.js",
    "70_integrations.js",
]

CSS_FILES = [
    "00_tokens.css",
    "01_base_layout.css",
    "02_components.css",
    "03_pages.css",
    "10_desktop_shell.css",
    "20_tablet.css",
    "30_mobile.css",
    "40_small_mobile.css",
    "50_desktop_enhancements.css",
    "51_wide_desktop.css",
]


def _minify_css(text):
    """String-aware CSS compression (comments + whitespace runs outside strings).

    Quoted strings are copied byte-for-byte, so content/url() values never
    change. Whitespace runs collapse to a single space, which CSS treats as
    equivalent anywhere outside strings.
    """
    out = []
    i = 0
    n = len(text)
    while i < n:
        if text.startswith("/*", i):
            end = text.find("*/", i + 2)
            i = n if end == -1 else end + 2
            if out and not out[-1].isspace():
                out.append(" ")
            continue
        ch = text[i]
        if ch in "\"'":
            quote = ch
            j = i + 1
            while j < n:
                if text[j] == "\\":
                    j += 2
                    continue
                if text[j] == quote:
                    j += 1
                    break
                j += 1
            out.append(text[i:j])
            i = j
            continue
        if ch.isspace():
            j = i
            while j < n and text[j].isspace():
                j += 1
            if out and not out[-1].isspace():
                out.append(" ")
            i = j
            continue
        out.append(ch)
        i += 1
    return "".join(out).strip()


def bundle(files, source_dir, target, header, minify=False):
    chunks = [header.rstrip(), ""]
    for name in files:
        path = source_dir / name
        chunks.append(f"/* source: {path.relative_to(ROOT).as_posix()} */")
        chunks.append(path.read_text(encoding="utf-8").strip())
        chunks.append("")
    text = "\n".join(chunks).rstrip() + "\n"
    if minify:
        text = _minify_css(text) + "\n"
    target.write_text(text, encoding="utf-8")


def main():
    bundle(
        JS_FILES,
        JS_SRC,
        STATIC / "app.js",
        "// Generated by app/tools/build_static.py. Edit app/static/src/js/* instead.",
    )
    bundle(
        CSS_FILES,
        CSS_SRC,
        STATIC / "styles.css",
        "/* Generated by app/tools/build_static.py. Edit app/static/src/css/* instead. */",
        minify=True,
    )


if __name__ == "__main__":
    main()
