from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "static"
JS_SRC = STATIC / "src" / "js"
CSS_SRC = STATIC / "src" / "css"

JS_FILES = [
    "00_state.js",
    "10_shell.js",
    "20_tmdb_home.js",
    "21_tmdb_cards.js",
    "22_tmdb_detail.js",
    "30_emby.js",
    "40_subscriptions_view.js",
    "41_subscription_cards.js",
    "42_subscription_resources.js",
    "50_logs.js",
    "60_settings_view.js",
    "61_settings_sources_model.js",
    "62_settings_sources_view.js",
    "63_settings_sources_actions.js",
    "64_settings_actions.js",
    "70_integrations.js",
]

CSS_FILES = [
    "00_tokens.css",
    "01_base_layout.css",
    "02_components.css",
    "03_pages.css",
    "10_desktop_shell.css",
    "20_tablet.css",
    "30_mobile.css",
    "40_small_mobile.css",
    "50_desktop_enhancements.css",
    "51_wide_desktop.css",
]

def bundle(files, source_dir, target, header):
    chunks = [header.rstrip(), ""]
    for name in files:
        path = source_dir / name
        chunks.append(f"/* source: {path.relative_to(ROOT).as_posix()} */")
        chunks.append(path.read_text(encoding="utf-8").strip())
        chunks.append("")
    target.write_text("\n".join(chunks).rstrip() + "\n", encoding="utf-8")


def main():
    bundle(
        JS_FILES,
        JS_SRC,
        STATIC / "app.js",
        "// Generated by app/tools/build_static.py. Edit app/static/src/js/* instead.",
    )
    bundle(
        CSS_FILES,
        CSS_SRC,
        STATIC / "styles.css",
        "/* Generated by app/tools/build_static.py. Edit app/static/src/css/* instead. */",
    )


if __name__ == "__main__":
    main()
